# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from proto.boggle import boggle_pb2 as proto_dot_boggle_dot_boggle__pb2


class BoggleLobbyStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetWelcomeMessage = channel.unary_unary(
        '/boggle.BoggleLobby/GetWelcomeMessage',
        request_serializer=proto_dot_boggle_dot_boggle__pb2.Empty.SerializeToString,
        response_deserializer=proto_dot_boggle_dot_boggle__pb2.Greeting.FromString,
        )


class BoggleLobbyServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetWelcomeMessage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_BoggleLobbyServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetWelcomeMessage': grpc.unary_unary_rpc_method_handler(
          servicer.GetWelcomeMessage,
          request_deserializer=proto_dot_boggle_dot_boggle__pb2.Empty.FromString,
          response_serializer=proto_dot_boggle_dot_boggle__pb2.Greeting.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'boggle.BoggleLobby', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
