# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/boggle/boggle.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/boggle/boggle.proto',
  package='boggle',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x19proto/boggle/boggle.proto\x12\x06\x62oggle\"\x07\n\x05\x45mpty\"\x1c\n\x08Greeting\x12\x10\n\x08greeting\x18\x01 \x01(\t2E\n\x0b\x42oggleLobby\x12\x36\n\x11GetWelcomeMessage\x12\r.boggle.Empty\x1a\x10.boggle.Greeting\"\x00\x62\x06proto3'
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='boggle.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=44,
)


_GREETING = _descriptor.Descriptor(
  name='Greeting',
  full_name='boggle.Greeting',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='greeting', full_name='boggle.Greeting.greeting', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=74,
)

DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['Greeting'] = _GREETING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'proto.boggle.boggle_pb2'
  # @@protoc_insertion_point(class_scope:boggle.Empty)
  })
_sym_db.RegisterMessage(Empty)

Greeting = _reflection.GeneratedProtocolMessageType('Greeting', (_message.Message,), {
  'DESCRIPTOR' : _GREETING,
  '__module__' : 'proto.boggle.boggle_pb2'
  # @@protoc_insertion_point(class_scope:boggle.Greeting)
  })
_sym_db.RegisterMessage(Greeting)



_BOGGLELOBBY = _descriptor.ServiceDescriptor(
  name='BoggleLobby',
  full_name='boggle.BoggleLobby',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=76,
  serialized_end=145,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetWelcomeMessage',
    full_name='boggle.BoggleLobby.GetWelcomeMessage',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_GREETING,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BOGGLELOBBY)

DESCRIPTOR.services_by_name['BoggleLobby'] = _BOGGLELOBBY

# @@protoc_insertion_point(module_scope)
